services:
  - type: web
    name: schedule-manager-api
    env: node
    nodeVersion: 16.x
    rootDir: backend
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
